version: "3.9"
services:
  server:
    image: nginx
    container_name: server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
  app1:
    image: nginx
    container_name: app1
    ports:
      - "80"
    volumes:
      - ./app1/index.html:/usr/share/nginx/html/index.html
  app2:
    image: nginx
    container_name: app2
    ports:
      - "80"
    volumes:
      - ./app2/index.html:/usr/share/nginx/html/index.html
  app3:
    image: nginx
    container_name: app3
    ports:
      - "80"
    volumes:
      - ./app3/index.html:/usr/share/nginx/html/index.html