---
all:
  hosts:
    k8s-master:
    k8s-worker1:
    k8s-worker2:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_user: vagrant
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

masters:
  hosts:
    k8s-master:
      ansible_host: 192.168.100.12

workers:
  hosts:
    k8s-worker1:
      ansible_host: 192.168.100.13
    k8s-worker2:
      ansible_host: 192.168.100.14